import type { Tweet } from '../types';

export const mockTweets: Tweet[] = [
  {
    id: '1',
    author: {
      id: '1',
      username: 'elonmusk',
      displayName: 'Elon Musk',
      avatar: 'https://pbs.twimg.com/profile_images/1683325380441128960/yGsN4J5Q_400x400.jpg',
      verified: true,
      followersCount: 150000000,
      followingCount: 100,
    },
    content: 'Twitter is now X. The everything app is coming.',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    likesCount: 45000,
    retweetsCount: 12000,
    repliesCount: 8500,
    isLiked: false,
    isRetweeted: false,
    isBookmarked: false,
  },
  {
    id: '2',
    author: {
      id: '2',
      username: 'sundarpichai',
      displayName: 'Sundar Pichai',
      avatar: 'https://pbs.twimg.com/profile_images/1572692188940939265/6lQhJW3P_400x400.jpg',
      verified: true,
      followersCount: 5000000,
      followingCount: 500,
    },
    content: 'Excited to share our latest AI advances at Google I/O. The future of search is here with generative AI.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    likesCount: 25000,
    retweetsCount: 8000,
    repliesCount: 3200,
    isLiked: true,
    isRetweeted: false,
    isBookmarked: true,
  },
  {
    id: '3',
    author: {
      id: '3',
      username: 'satyanadella',
      displayName: 'Satya Nadella',
      avatar: 'https://pbs.twimg.com/profile_images/1480735024538869761/9EJ8J3QG_400x400.jpg',
      verified: true,
      followersCount: 3000000,
      followingCount: 200,
    },
    content: 'AI is the defining technology of our time. At Microsoft, we are committed to building AI responsibly and making it accessible to everyone.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    likesCount: 18000,
    retweetsCount: 5500,
    repliesCount: 2100,
    isLiked: false,
    isRetweeted: true,
    isBookmarked: false,
  },
  {
    id: '4',
    author: {
      id: '4',
      username: 'tim_cook',
      displayName: 'Tim Cook',
      avatar: 'https://pbs.twimg.com/profile_images/1480735024538869761/9EJ8J3QG_400x400.jpg',
      verified: true,
      followersCount: 12000000,
      followingCount: 300,
    },
    content: 'Privacy is a fundamental human right. At Apple, we build products that protect your personal information by design.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    likesCount: 32000,
    retweetsCount: 9000,
    repliesCount: 4500,
    isLiked: true,
    isRetweeted: false,
    isBookmarked: false,
  },
  {
    id: '5',
    author: {
      id: '5',
      username: 'jeffbezos',
      displayName: 'Jeff Bezos',
      avatar: 'https://pbs.twimg.com/profile_images/1480735024538869761/9EJ8J3QG_400x400.jpg',
      verified: true,
      followersCount: 5000000,
      followingCount: 100,
    },
    content: 'Blue Origin is making progress on New Glenn. The future of space exploration is bright.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    likesCount: 15000,
    retweetsCount: 4000,
    repliesCount: 1800,
    isLiked: false,
    isRetweeted: false,
    isBookmarked: false,
  },
  {
    id: '6',
    author: {
      id: '6',
      username: 'billgates',
      displayName: 'Bill Gates',
      avatar: 'https://pbs.twimg.com/profile_images/1480735024538869761/9EJ8J3QG_400x400.jpg',
      verified: true,
      followersCount: 60000000,
      followingCount: 200,
    },
    content: 'Just finished reading "The Coming Wave" by Mustafa Suleyman. A must-read for anyone thinking about AI and the future.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    likesCount: 22000,
    retweetsCount: 6500,
    repliesCount: 2800,
    isLiked: true,
    isRetweeted: true,
    isBookmarked: true,
  },
  {
    id: '7',
    author: {
      id: '7',
      username: 'jack',
      displayName: 'Jack Dorsey',
      avatar: 'https://pbs.twimg.com/profile_images/1480735024538869761/9EJ8J3QG_400x400.jpg',
      verified: true,
      followersCount: 6000000,
      followingCount: 5000,
    },
    content: 'Building on Bitcoin. The open protocol for the internet of value.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    likesCount: 12000,
    retweetsCount: 3500,
    repliesCount: 1500,
    isLiked: false,
    isRetweeted: false,
    isBookmarked: false,
  },
  {
    id: '8',
    author: {
      id: '8',
      username: 'vitalikbuterin',
      displayName: 'Vitalik Buterin',
      avatar: 'https://pbs.twimg.com/profile_images/1480735024538869761/9EJ8J3QG_400x400.jpg',
      verified: true,
      followersCount: 5000000,
      followingCount: 2000,
    },
    content: 'Ethereum scaling is progressing well. Rollups are the future and they are here now.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    likesCount: 18000,
    retweetsCount: 5000,
    repliesCount: 2200,
    isLiked: true,
    isRetweeted: false,
    isBookmarked: false,
  },
];

export const mockUser = {
  id: 'current-user',
  username: 'kartiksharma',
  displayName: 'Kartik Sharma',
  avatar: 'https://via.placeholder.com/150',
  verified: false,
  bio: 'AI Engineer | Linux Architect | Python Dev',
  followersCount: 1000,
  followingCount: 500,
};